version: '3'
services:
  cassandra:
    image:  cassandra:3.11
    environment:
      - CASSANDRA_CLUSTER_NAME='Cassandra Terrform Provider Test Cluster'
    ports:
      - 9042:9042
    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml